### ISSUE TITLE
Secret access key with `/`: invalid port ... after host

### ISSUE THREAD

**Issue by eriksw** [google/apt-golang-s3#11]
If there is a `/` character in the secret access key, the url parsing fails with an error like this:

`General failure: parse "s3://AKIA...:B.../...A@s3.amazonaws.com/my-bucket/.../InRelease": invalid port ":B.../...A" after host`

This can be worked around by double-urlencoding the secret access key in the sources file (apt seems to remove one layer of urlencoding).

However, the string does make it through to the transport binary (that error is coming from `url.Parse`) cleanly, so this _could_ be handled entirely within the transport, such as by pre-processing the url before it is passed to `url.Parse`.

**Comment by adamvduke** [comment]
I'll take a look at this.
